apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebserver
  labels:
    app: simplewebserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplewebserver
  template:
    metadata:
      labels:
        app: simplewebserver
    spec:
      containers:
      - name: simplewebserver
        image: pritesk1/devops-challenge-entry-particle41
        ports: 
        - containerPort: 80
        name: nginx
        volumeMounts:
        - name: htmlcontent
          mountPath: "/usr/share/nginx/html/"
          readOnly: true
      volumes:
      - name: htmlcontent
        configMap:
          name: index.html
          items:
          - key: index.html
            path: index.html